name: schulz_et_al_2023
channels:
  - intel
  - conda-forge
dependencies:
  - python=3.9
  - omegaconf
  - ca-certificates
  - openssl
  - ipykernel
  - zarr
  - dask=2022.8.0
  - tqdm
  - dask-jobqueue=0.7.4
  - nodejs
  - jupyter
  - jupyterlab
  - dask-labextension
  - certifi
  - distributed==2022.9.2
  - netcdf4
  - intake
  - matplotlib
  - dvc==2.38.1
  - hvplot
  - datashader=0.13.0
  - cmcrameri
  - haversine
  - seaborn
  - go
  - nc-time-axis
  - pydap
  - metpy
  - python-graphviz
  - netcdf-fortran
  - fftw
  - filelock
  - pyarrow
  - pytables
  - conda-build
  - pint-xarray
  - pytest
  - black
  - xarray-datatree==0.0.10
  - flox
  - xarray==2022.10.0
  - cartopy
  - fire
  - cfgrib
  - tree
  - pandas=1.5.1
  - mpld3
  - ipdb
  - ffmpeg
  - anaconda-client
  - satdownload
  - dvc-webdav
  - selenium
  - firefox
  - geckodriver
